spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/hapi_fhir
    username: hapi_fhir_admin
    password: hapi_fhir_adminpw
    driver-class-name: org.postgresql.Driver
    max-active: 15
    hikari:
      maximum-pool-size: 10
      auto-commit: false
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect

keycloak:
  auth-server-url: https://keycloak.dev.sid-indonesia.org/auth
  realm: hapi-fhir
  resource: dev-client
  public-client: true

hapi:
  fhir:
#    server_address: https://hapi-fhir.dev.sid-indonesia.org/fhir
    mdm_enabled: false
    delete_expunge_enabled: true
#    default_resource_encoding: JSON
    inline_resource_storage_below_size: 2147483647 # Integer.MAX_VALUE
#    dao_scheduling_enabled: false
