# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Tests & Build

on:
  push:
    branches: [sid]
  pull_request:
    branches: [sid]

jobs:
  build:
    name: Run Tests & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Override Maven `settings.xml` with mirrors section
        uses: s4u/maven-settings-action@v2.4.1
        with:
          mirrors: '[{"id": "nexus-sid", "mirrorOf": "*", "url": "${{ secrets.NEXUS_URL }}"}]'

      - name: Build with Maven + Code Analysis with SonarQube
        run: mvn -B clean package sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }}
