# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [sid]
  pull_request:
    branches: [sid]

jobs:
  build:
    name: Run Tests & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven + Code Analysis with SonarQube
        run: mvn -B clean integration-test package sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }}

      - name: Upload WAR
        uses: actions/upload-artifact@v2
        with:
          name: executable-war
          path: target/*.war

  deploy-to-dev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR from build
        uses: actions/download-artifact@v2
        with:
          name: executable-war

      - name: Set file name
        run: echo "::set-output name=FILE_NAME::`basename *.war`"
        id: file-name-setter

      - name: Copy WAR via SSH with key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          source: ${{ steps.file-name-setter.outputs.FILE_NAME }}
          target: "downloads/hapi-fhir-jpaserver"

      - name: Execute remote scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            echo "${{ secrets.SSH_USER_PASSWORD_DEV }}" | \
            sudo -S ./deploy-hapi-fhir-jpaserver.sh