# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to dev

on:
  push:
    branches: [sid]

jobs:
  build:
    name: Run Tests & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package

      - name: Upload WAR
        uses: actions/upload-artifact@v3
        with:
          name: ROOT.war
          path: target/ROOT.war

  deploy-to-dev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR from build
        uses: actions/download-artifact@v3
        with:
          name: ROOT.war

      - name: Copy WAR via SSH with key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          source: ROOT.war
          target: "downloads/hapi-fhir-jpaserver"

      - name: Sleep for 10s to wait for Tomcat re-deploy WAR
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 10s

      - name: Wait until the FHIR server is ready
        uses: mydea/action-wait-for-api@v1
        with:
          method: "GET"
          url: "${{ secrets.SID_HAPI_FHIR_DEV_URL }}/fhir/metadata"
          expected-status: "200"
          timeout: 180
          interval: 1
