# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Executable WAR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Override Maven `settings.xml` with mirrors section
        uses: s4u/maven-settings-action@v2.4.1
        with:
          mirrors: '[{"id": "nexus-sid", "mirrorOf": "*", "url": "${{ secrets.NEXUS_URL }}"}]'

      - name: Run tests
        run: mvn -B clean test

      - name: Run integration tests
        run: mvn -B clean integration-test

      - name: Build WAR
        run: mvn -B package

      - name: Upload WAR
        uses: actions/upload-artifact@v2
        with:
          name: executable-war
          path: target/*.war

  release:
    name: Release WAR
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR from build
        uses: actions/download-artifact@v2
        with:
          name: executable-war

      - name: Set file name
        run: echo "::set-output name=FILE_NAME::`basename *.war`"
        id: file-name-setter

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.file-name-setter.outputs.FILE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
