# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Executable WAR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build WAR
        run: mvn -B package

      - name: Upload WAR
        uses: actions/upload-artifact@v3
        with:
          name: ROOT.war
          path: target/ROOT.war

  release:
    name: Release WAR
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR from build
        uses: actions/download-artifact@v3
        with:
          name: ROOT.war

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ROOT.war
          token: ${{ secrets.GITHUB_TOKEN }}
